config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotes
  root "quotes#index"
end

app/models/quote.rb
class Quote < ActiveRecord::Base
    validates :name, :description, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :quotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :find_quote, only: [:show, :edit, :update, :destroy]
    
    def index
        @quotes = Quote.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
      @quote = current_user.quotes.build
    end
    
    def create
        @quote = current_user.quotes.build(quote_params)
        
        if @quote.save
            redirect_to @quote, notice: "Quote was successfully created."
        else
            render "new"
        end
    end
    
    def edit
    end

    def update
        if @quote.update(quote_params)
            redirect_to @quote, notice: "Quote was successfully updated."
        else
            render 'edit'
        end
    end
    
    def destroy
        @quote.destroy
        redirect_to root_path
    end
    
    private
    
    def quote_params
        params.require(:quote).permit(:name, :description)
    end
    
    def find_quote
        @quote = Quote.find(params[:id])
    end
end

app/controllers/random_controller.rb
class RandomController < ApplicationController
    before_action :find_quote, only: [:show, :edit, :update, :destroy]
    
    def index
        @quotes = Quote.all
    end
    
    def new
        @quote = Quote.find(params[:id])
    end

    private
    
    def quote_params
        params.require(:quote).permit(:name, :description)
    end
    
    def find_quote
        @quote = Quote.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/random_helper.rb
module RandomHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Quotestream
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags 
%body
  %nav.navbar.navbar-default 
    .container
      .navbar-brand.navbar-nav= link_to "Quotestream", root_path
      
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Quote", new_quote_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Log In", new_user_session_path
          
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
  
    = yield

app/views/quotes/_form.html.haml
= simple_form_for @quote, html: {multipart: true} do |f|
    - if @quote.errors.any?
        #errors
        %h3
            = pluralize(@quote.errors.count, "error")
            Prevented this quote from saving
            %ul
                - @quote.errors.full_messages.each do |msg|
                    %li= msg
    
    .form-group
        = f.input :name, input_html: {class: "form-control"}
            
    .form-group
        = f.input :description, input_html: {class: "form-control"}
    
    = f.button :submit, class: "btn btn-primary"

app/views/quotes/edit.html.haml
%h1 Edit Quote

= render 'form'
%br/
%p
    = link_to 'Cancel', quote_path, class: "btn btn-primary"
    = link_to 'Delete', quote_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"

app/views/quotes/index.html.haml
- @quotes.each do |quote|
    %p= link_to quote.description, quote, {:style => "font-family: Verdana;"}

app/views/quotes/new.html.haml
%h1 Add a Quote

= render 'form'
%br/
%p
    = link_to "Back", root_path, class: "btn btn-primary"

app/views/quotes/show.html.haml
%blockquote 
    %p= @quote.description
    %p
        %small= @quote.name
%p Submitted by: 
= @quote.user_id
at
= @quote.created_at


%br/
%br/
%p
    = link_to "Back", root_path, class: "btn btn-primary"
    = link_to "Edit", edit_quote_path, class: "btn btn-primary"
    = link_to "Delete", quote_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"

app/views/random/index.html.haml
%blockquote 
    %p= @quote.description
    %p
        %small= @quote.name
%p Submitted by: 
= @quote.user.email

%br/
%br/
%p
    = link_to "Back", root_path, class: "btn btn-primary"
    = link_to "Edit", edit_quote_path, class: "btn btn-primary"
    = link_to "Delete", quote_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"